<a href="https://colab.research.google.com/github/itzdeepanshu30/Deep-Learnig-google-_Collab_notebook/blob/main/00_pytorch_fund.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

if to have question :https://github.com/mrdbourke/pytorch-deep-learning/discussions

REsource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [ ]:
!nvidia-smi

Mon Aug 26 08:32:55 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
scalar= torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
Matrix= torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

RANDOM TENSOR


### Random tensor
Why random tensor ?

Random tensor are imp becacuse the way many neural networks learn is that they start with tensor with tensor full of random number then adjust those random number to better repersent the data .

`start with random number -> look at data->update random number->look at data ->update random numbers`

Torch random tensor -https://pytorch.org/docs/stable/generated/torch.rand.html

# New Section

In [ ]:
### create a random of tensor of size  (3,4)
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.1054, 0.1108, 0.7076, 0.8115],
         [0.3950, 0.2824, 0.8293, 0.4345],
         [0.2470, 0.2769, 0.8805, 0.3017]]])

In [ ]:
### create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(3,244,244)) # height ,width , color channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)